name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # Synchronisation toutes les heures
  workflow_dispatch:    # Bouton manuel

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream changes
        uses: aandreww/github-fork-sync-action@v1.1
        with:
          upstream_repository: jaywcjlove/awesome-mac
          upstream_branch: master
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
